### ISSUE TITLE
Doesn't build with Stack 1.7.1

### ISSUE THREAD

**Issue by mrehayden1** [sseefried/open-epidemic-game#3]
Moving the external packages to extra-deps fixes it.

```
extra-deps:
- git: https://github.com/sseefried/hsSDL2
  commit: 4de086d61d17326f2ee9a1ca1aa98c61ebbc9c76
- git: https://github.com/sseefried/hs-sdl2-mixer
  commit: e6bd509a59fc4907d01b49309c2e381e4ec04a1e
- git: https://github.com/sseefried/hs-cairo
  commit: 922c6fab2d632c220ebd3f07b737e75537bfda70
- git: https://github.com/sseefried/HipMunk
  commit: 1e9c64f291cc2056e55b4405d117fe40b0161bb2
- git: https://github.com/sseefried/freetype2
  commit: 185ba5e991592cb84a8a52fabdb798797ad4f3ba
- git: https://github.com/sseefried/hs-sdl2-image
  commit: 1a7ef66baf96455411433898acab3589f1c4d73d
- git: https://github.com/sseefried/OpenGLRaw
  commit: c14b666c244cfcb2cda4708b21360c7ff21b342e
```
